version: '3'
services:
  mysql:
    platform: linux/x86_64
    build: ./db
    environment:
      MYSQL_ROOT_PASSWORD: nft12345
      MYSQL_DATABASE: discord_home
    volumes:
      - ./db/mysql_data:/var/lib/mysql
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./db/sql:/docker-entrypoint-initdb.d
    ports:
      - '3310:3306'
    command: --innodb-use-native-aio=0
    restart: always
volumes:
  mysql:
