import { GuildItem } from '#/common/types/Guild';
import { SaveBtn } from '@/components/common/SaveBtn';
import { ToggleAutoGeneration } from '@/components/common/ToggleAutoGeneration';
import ErrorMessage from '@/components/utils/ErrorMessage';
import Title from '@/components/utils/Title';
import useInputField from '@/hooks/utils/useInputField';
import useValidate from '@/hooks/utils/useValidation';
import { post } from '@/utils/apiHelper';
import { useToast } from '@chakra-ui/react';
import { useState } from 'react';
import 'react-datepicker/dist/react-datepicker.css';

type Props = {
  guild: GuildItem;
};
export const GuildDescriptionForm: React.FC<Props> = (props) => {
  const toast = useToast();
  const [generateAuto, setGenerateAuto] = useState(
    props.guild.autoGenerateDescription
  );

  const {
    inputField: descriptionInputField,
    valueState: description,
    setValueState: setDescription,
  } = useInputField({
    id: 'description',
    type: 'textarea',
    value: props.guild.description,
    rows: 10,
    disabled: generateAuto,
  });

  // Validations
  const { validationResults, isValidAll } = useValidate([
    {
      name: 'description',
      value: description,
      required: true,
      max: 2000,
    },
  ]);

  const save = async () => {
    try {
      if (!isValidAll()) {
        return;
      }
      await post(`/api/guild/update/${props.guild.id}`, {
        description,
      });
      toast({
        status: 'success',
        description: 'Saved',
      });
    } catch (error) {
      toast({
        status: 'error',
        description: 'Failed',
        isClosable: true,
      });
    }
  };

  return (
    <>
      <Title title="Description" />
      <div className="h-5" />
      <div className="flex justify-end">
        <ToggleAutoGeneration
          guildId={props.guild.id}
          target="description"
          isChecked={generateAuto}
          onChange={(value) => {
            setGenerateAuto(value);
          }}
        />
      </div>
      <div className="h-5" />
      {descriptionInputField}
      <ErrorMessage
        label="image"
        message={validationResults.description?.message}
      />
      <div className="flex justify-end m-2">
        <SaveBtn onClick={() => save()} disabled={generateAuto} />
      </div>
    </>
  );
};
