name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/app/discord-home &&
            git pull origin main &&
            cd /var/app/discord-home/backend &&
            npm install &&
            npx dotenv -e .env.production.local -- npx prisma migrate deploy &&
            npx dotenv -e .env.production -- dotenv -e .env.production.local -- ts-node --require ./ts-node-require.ts prisma/seeds/index.ts &&
            cd /var/app/discord-home/frontend &&
            npm install && npm run build &&
            pm2 restart discord-home
